### ISSUE TITLE
abbreviations should be consistent

### ISSUE THREAD

**Issue by tboetig** [embedly/embedly-docs#11]
some places it's JSON, others its json.  same for URL/url

**Comment by TrevorBurnham** [comment]
I've been making them consistently capitalized as I've been rewriting things. Note that the rewrite is on the separate [rewrite branch](https://github.com/embedly/embedly-docs/tree/rewrite) except to the extent that the rewrites are deemed urgently needed to complement the search feature so that search can launch immediately, whereas the full docs rewrite will take a few more weeks.

**Comment by TrevorBurnham** [comment]
Closing, as this isn't addressable without combing over every page in the docs. Please correct or let me know about any individual inconsistencies.
