### ISSUE TITLE
Add doc on using jsonp w/ auth

### ISSUE THREAD

**Issue by artgibson** [embedly/embedly-docs#4]
We should add some documentation on how to secure API requests via jsonp or xml-rpc calls. This is a combination of our referrers and ip whitelisting and oAuth.

**Comment by TrevorBurnham** [comment]
Could you elaborate on how the referrer/IP whitelisting enters into it? Is whitelisting a prerequisite for oAuth to work? http://embed.ly/docs/auth doesn't mention this.

By the way, there's a small HTML/CSS glitch in the dashboard that's causing this:

![](http://cl.ly/0v2u0u080V1B3F201T01/Screen%20Shot%202012-05-02%20at%205.32.45%20PM.png)

I would change the text to "You can use the following special characters:", make `dd` and `dt` `display: inline` instead of `display: block`, and add `margin-right: 10px` to the `dd`. With those changes, it'll look like this:

![](http://cl.ly/3m3x2q1n3k2L1c3L0h3g/Screen%20Shot%202012-05-02%20at%205.42.13%20PM.png)

This applies to both the referrers page and the IP page.

**Comment by artgibson** [comment]
Here is a quick blog post we wrote: http://blog.embed.ly/securing-keys

Let me know if you have other questions on it. I'll update the css, actually just noticed that too.

**Comment by TrevorBurnham** [comment]
Pushed a new version of the authentication page to the rewrite branch: https://github.com/embedly/embedly-docs/commit/04342f0733588fec06a4bbbbd07fcc9f2242cad5#diff-0.

It's shorter and more focused, and covers the referrer/IP whitelisting.
