### ISSUE TITLE
In page navigation.

### ISSUE THREAD

**Issue by screeley** [embedly/embedly-docs#6]
http://wwwng.embed.ly/docs/endpoints/1/oembed does not have in page navigation on the left hand side, http://embed.ly/docs/endpoints/1/oembed does. 

Again it helps with discovery.

**Comment by TrevorBurnham** [comment]
Yes, Art and I have discussed this. The solution we reached was to add a table of contents at the top of longer pages (as Wikipedia does). I haven't implemented this yet, though.

**Comment by screeley** [comment]
Perfect. Before we lunch search I'd like #5 and #6 in. I don't want to hurt discovery because of it.

We should also talk about adding mixpanel to track how people move through embed.ly.

**Comment by TrevorBurnham** [comment]
This issue fixed by https://github.com/embedly/embedly-www/commit/22a9d16c9dc770f3a024c50b8b3b467b25a3ac42. The ToC is generated via JavaScript for articles with more than 3 subheadings.

Here's what it looks like:

![](http://f.cl.ly/items/2D1p0R3B3z1I2l2t2j1y/Screen%20Shot%202012-05-19%20at%2011.20.55%20AM.png)
